host: http://inlets.saltbo.cn/
root: ../moreu-front/dist
secret: 1111

email:
  host: smtpdm.aliyun.com:25
  user: no-reply@saltbo.fun
  password: mG077URe2Wh9

database:
  driver: mysql
  dsn: root:admin@(localhost:3306)/moreu?charset=utf8&parseTime=True&loc=Local

routers:
  - pattern: /api
    upstream:
      address: http://localhost:8081
      headers:
        Authorization: f1h6lVxxxxxxxxxxxxxxxxxxxxxXJkIo3
