host: http://inlets.saltbo.cn/
#moreu: ../moreu-front/dist
secret: 1111

email:
  host: smtpdm.aliyun.com:25
  sender: no-reply@saltbo.fun
  username: Moreu
  password: mG077URe2Wh9

database:
  driver: mysql
  dsn: root:admin@(localhost:3306)/moreu?charset=utf8&parseTime=True&loc=Local

#database:
#  driver: sqlite3
#  dsn: moreu.db

routers:
  - pattern: /
    upstream:
      address: http://localhost:8222

#statics:
#  - pattern: /
#    distDir: ../zpan-front/dist
