root: ../zpan-front/dist
secret: 1111

database:
  driver: mysql
  dsn: root:admin@(localhost:3306)/moreu?charset=utf8&parseTime=True&loc=Local

oauth2:
  authUrl: https://github.com/login/oauth/authorize
  tokenUrl: https://github.com/login/oauth/access_token
  userUrl: https://api.github.com/user
  clientId: de0c54393500d5a62510
  clientSecret: b171be4c6540a50c075f1a303c37998990e81153
  scope: user

roles:
  loader: ./roles.yml
  upstream:
    address: http://localhost:9312/api/member-roles
    headers:
      Authorization: f1h6lVxxxxxxxxxxxxxxxxxxkIo3

routers:
  - pattern: /api
    upstream:
      address: http://localhost:8081
      headers:
        Authorization: f1h6lVxxxxxxxxxxxxxxxxxxxxxXJkIo3
